spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasksapi
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgresql}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect